docker compose down
docker compose up --build --detach

# Get the container ID/Name generated by docker compose for this folder
$containerName = (docker compose ps -q | Select-Object -First 1)

if (-not $containerName) {
    Write-Host "No running container found." -ForegroundColor Red
    exit 1
}

Write-Host "Tailing logs for container ID: $containerName..." -ForegroundColor Green
docker logs -f $containerName